### PR TITLE
WorldBorder & Bastion Awareness

### PR DESCRIPTION
**Pull request by suirad**
Adds a soft dependency of Worldborder. Also has it check for it and makes sure chosen spawn locations are within world border. Should affect all cases where the plugin is used to choose the spawn.

### CODE REVIEW

**Comment by suirad** [comment]
@rourke750 @erocs @ttk2

**Comment by ttk2** [comment]
so does this remove the need to configure?.

**Comment by suirad** [comment]
It doesn't remove the need, just adds a check to make sure the picked location is for sure within world border. But i suppose it wouldnt be difficult to simplfy it to only use world border data and not config. Would you want that? Figured you wouldn't because i know you like having external configed things

**Comment by ttk2** [comment]
not really sure right now, the other changes (proximity spawning) are somthing I am more concerned about so I was going to merge that first .

**Comment by suirad** [comment]
I was about to recommend that as well. Figured a guarantee that world border would stay happy would help

**Comment by suirad** [comment]
@ttk2 i found where i need to patch in bastions to be able to add bastions checks too. Want me to go ahead and do that and add a second commit for it? My changes shouldn't conflict with soerxpsos pull, so they could both be merged independently.

**Comment by ttk2** [comment]
sounds good, go for it.

**Comment by suirad** [comment]
Alright cool. Im about to go eat real quick, but expect a pull for bastions shortly. Should be a 1 line change.

**Comment by suirad** [comment]
Both pulls have been made. This last commit requires the below pull to be merged:
https://github.com/Civcraft/Bastion/pull/19

**Comment by suirad** [comment]
@ttk2 good to merge

**Comment by ttk2** [comment]
cool please add a liscense.txt and make a clear indication that Suirad added this, its a requirement of GPL  :(

**Comment by suirad** [comment]
Do i need to add something over every lines that i added? And how is the lincense.txt supposed to be formatted?

**Comment by ttk2** [comment]
grab this http://dev.bukkit.org/licenses/7-gnu-general-public-license-version-3-gplv3/

just add the commit name or somthing and the date.

**Comment by erocs** [comment]
I don't think we need commit details, just individual contributor names.

**Comment by erocs** [comment]
BTW, where did we see that the original author made this GPLv3? Since he
doesn't have a licence in there, we'll have to make sure he's in the
licence file we add and probably link back to the location where he says
it's GPLv3.

**Comment by suirad** [comment]
Just squashed all of the commits into one, check out the licence.txt i added. Let me know how to improve it.

**Comment by ttk2** [comment]
its on bukkit dev, he links to the license there.

**Comment by ttk2** [comment]
good to merge now Erocs?

**Comment by erocs** [comment]
Let's add something along the lines of...

"Licensed GPLv3 by the original author josvth at
http://dev.bukkit.org/bukkit-plugins/random-spawn on March 19, 2012."

**Comment by ttk2** [comment]
sound good to me.

**Comment by suirad** [comment]
...So my wifi hotspot ran out of data... 
Il update my commit tomorrow after i buy some gigs, unless you wanna merge and take care of it.

Being out of the country is a pain.

**Comment by ttk2** [comment]
its easier just to wait for a low priority thing like this. 

Thanks for the work.

**Comment by suirad** [comment]
Yea thats fine. I am working on xserver jukealert atm, should be functional
tonight. But again, cant make a pull till tomorrow. Just fyi. All that
really needs to be done for juke alert is just snitch messages right?

**Comment by erocs** [comment]
I didn't think we were going to push Jukealert messages cross shard.

**Comment by suirad** [comment]
It would make sense to, if the nether and end are moved to different
shards. As of right now you get snitch alerts in the nether and end. Ofc it
could be made configurable by server. Though, im not sure why you wouldn't
have snitch alerts cross shards other than hardmode.

**Comment by erocs** [comment]
They're already fairly over-powered. There's been talk of limiting the
report radius to nerf skynets somewhat. If they were restricted to
reporting only within their shard it would perform the same. I guess add it
and make it configurable and Ttk2 can do what he wants.

**Comment by suirad** [comment]
Sounds like a plan

**Comment by rourke750** [comment]
I believe I already made juke alerts cross server.

**Comment by suirad** [comment]
You did, i just did some touch ups and tested it out.

**Comment by ghost** [comment]
Can I merge this and put it on civtest now?

Oh, travis isn't building it though since it doesn't have a travis.yml yet.

**Comment by rourke750** [comment]
Ignore Travis we aren't using that.

**Comment by suirad** [comment]
Im not exactly sure what is wanted done for the license(an example would be lovely).
But the code itself is ready for merge.

**Comment by ttk2** [comment]
just slap something at the top, its good faith, not machine processed syntax.

**Comment by ttk2** [comment]
looks like this does need to be rebased after the other one, just add a liscense.txt please.

**Comment by suirad** [comment]
The licence.txt is there. See changes. 
This should be good to merge

**Comment by ttk2** [comment]
Nice will do when I get home.

**Comment by ttk2** [comment]
um this needs to be rebased

**Comment by suirad** [comment]
Will do

**Comment by suirad** [comment]
Rebased and quickly modified to adapt to new pull.
Good to merge.

**Comment by ttk2** [comment]
I will let @rourke750  look over this one.

**Comment by ttk2** [comment]
also make a build when you merge roruke, we don't have jenkins for this.

**Comment by rourke750** [comment]
There is a jenkins now.  I just need to update the maven repo.  I'll merge this.

**Comment by ttk2** [comment]
sweet, into testing this goes then. So lest see, WB awareness, Bastions awareness, and proximity spawning?

**Comment by suirad** [comment]
Correct

**Comment by ttk2** [comment]
waiting on RB to work in Jenkins then.

**Pull request merged**
