### PR TITLE
Spawning near random player

### PR DESCRIPTION
**Pull request by sepiatonal**
If nobody is online spawning works as before, otherwise it puts you within a 500 block radius of a random other player. I changed the example world.yml file to show how to set it up. I've tested it with some friends and it definitely works with 0-3 people online.

### CODE REVIEW

**Comment by ttk2** [comment]
Thanks for working on this! Do you know how to update this pull with the changes Erocs asked for?

**Comment by sepiatonal** [comment]
I should be able to get the exclusion zone working, although in my opinion a range of 200-500 might make more sense than 500-800. That way people still spawn within chat radius but they never spawn right on top of someone. This is actually the first I've heard of sky vaults. How do they work? Should we avoid spawning players on top of them by making it impossible to spawn on top of obsidian, or by making it impossible to spawn too high up? I think making it impossible to spawn on obsidian might be the best idea, as a little while ago a newfriend spawned randomly inside of Playpen and that would fix both problems.

I just got home so I'll get started on these changes tomorrow.

**Comment by erocs** [comment]
The ranges will be configurable so we can tweak it to the zone we want.  :)

They're only possible because of bastions, which protect the blocks above
them. Instead of defining a y-range for spawning, we should probably hook
into Bastion and prevent players from spawning within Bastion fields. You
added the WorldBorder hook already, so this would be a similar hook for
Bastion. Having a configurable list of block names which can't be spawned
on might be good too.

**Comment by suirad** [comment]
@erocs i had added the wb hook.

**Comment by ttk2** [comment]
We can just layer merges for the WB hook. Does Bastion even have a good way
to check if a given choord is in a field?

Anyways good work sorexpso

**Comment by suirad** [comment]
@ttk2 lets keep the bastion and wb stuff in my pull so we dont spill irrelevance into soerxpso's

**Comment by ttk2** [comment]
ok then, does this become a complete pull if we do that?

**Comment by ttk2** [comment]
so we we merge this? is the liscense stuff done?

**Comment by sepiatonal** [comment]
I've added support for an exclusion zone but I haven't tested that, as my friends for testing were unavailable. I'm fairly certain it should work, but we should probably use civtest to confirm that it works. There is and has been a list of blocks that are excluded from being spawned on in the worlds.yml file. The easiest way to go about stopping players from spawning on vaults is probably just to exclude obsidian.

**Comment by sepiatonal** [comment]
Alright, tested, then fixed, then tested. It definitely works now. I also did some refactoring so the code is better, and now when a circle area is being used you can specify a radius instead of the silly thing we had before where you had to specify 4 distances.

**Comment by ghost** [comment]
Ready for civtest?

**Comment by sepiatonal** [comment]
Yes.

**Comment by ttk2** [comment]
there we go, no way to get jenkins to make a build, that needs to be setup.

**Comment by ttk2** [comment]
Ok this is still waiting on a build. I will try and have one of the admins make one. It's mavenized do builds or adding to Jenkins should be easy.

**Pull request merged**
