### PR TITLE
update pom.xml

### PR DESCRIPTION
**Pull request by idoash4**
I updated the dependency from 1.6 to 1.8.3.

### CODE REVIEW

**Comment by idoash4** [comment]
@ttk2

**Comment by ttk2** [comment]
ok now its going onto Civtest. Do I need to do anything special for the bastion and wb awareness?

**Comment by idoash4** [comment]
ah the bastions thing is causing the problem.

**Comment by ttk2** [comment]
on civtest

**Comment by ttk2** [comment]
wait this was the wrong place for that

**Comment by rourke750** [comment]
Wrong plugin...

**Pull request merged**
